-- SELLER (15 записа, с AVERAGE_RATING = NULL)
INSERT INTO SELLER (COMPANY_NAME, COMPANY_EMAIL, AVERAGE_RATING, COUNTRY) VALUES
('TechNova Ltd',       'sales@technova.com',        NULL, 'Bulgaria'),
('Galaxy Traders',     'info@galaxytraders.com',    NULL, 'Germany'),
('Lenovo Outlet',      'contact@lenovo-outlet.com', NULL, 'Poland'),
('Dell Store',         'hello@dell-store.com',      NULL, 'Netherlands'),
('Audio World',        'support@audioworld.com',    NULL, 'Italy'),
('PhotoPro',           'orders@photopro.com',       NULL, 'France'),
('GameHub',            'hi@gamehub.com',            NULL, 'Spain'),
('HomeKitch',          'care@homekitch.com',        NULL, 'Bulgaria'),
('Book Planet',        'team@bookplanet.com',       NULL, 'UK'),
('BeautyCare',         'help@beautycare.com',       NULL, 'Romania'),
('FashionLine',        'sales@fashionline.com',     NULL, 'Bulgaria'),
('CleanHome',          'info@cleanhome.com',        NULL, 'Czechia'),
('SportStar',          'shop@sportstar.com',        NULL, 'Portugal'),
('ToyBox',             'hello@toybox.com',          NULL, 'Bulgaria'),
('AutoGear',           'contact@autogear.com',      NULL, 'Hungary');

-- CATEGORY (15 записа)
INSERT INTO CATEGORY (CATEGORY_NAME, [DESCRIPTION]) VALUES
('Electronics','General consumer electronics'),
('Phones','Smartphones and accessories'),
('Laptops','Notebooks and ultrabooks'),
('Audio','Headphones and speakers'),
('Cameras','Photo & video'),
('Appliances','Home appliances'),
('Gaming','Consoles and games'),
('Books','Books & ebooks'),
('Beauty','Cosmetics and care'),
('Fashion','Apparel and accessories'),
('Home','Home & living'),
('Sports','Sports goods'),
('Toys','Toys and games'),
('Automotive','Car accessories'),
('Garden','Garden supplies');

-- PRODUCT (50 записа)
INSERT INTO PRODUCT (NAME, BRAND, MODEL, [DESCRIPTION], PRICE, WARRANTY_MONTH, SELLER_ID, CATEGORY_ID) VALUES
('iPhone 14',            'Apple',    'A2882',  '128GB Midnight',                    799.99, 24, 1,  2),
('iPhone 14 Pro',        'Apple',    'A2890',  '256GB Space Black',                 1099.99, 24, 1,  2),
('iPhone 15',            'Apple',    'A3102',  '128GB Blue',                        899.99, 24, 1,  2),
('Galaxy S23',           'Samsung',  'SM-S911', '128GB Phantom',                    749.99, 24, 2,  2),
('Galaxy S23 Ultra',     'Samsung',  'SM-S918', '256GB Green',                      999.99, 24, 2,  2),
('Galaxy A55',           'Samsung',  'SM-A556', '128GB Awesome Blue',               499.99, 24, 2,  2),
('IdeaPad 3',            'Lenovo',   '15ADA6', '15.6\" FHD Ryzen 5',                599.99, 24, 3,  3),
('ThinkPad X1',          'Lenovo',   'Gen 11',  'Core i7 32GB RAM',                 1399.99, 24, 3,  3),
('Legion 5 Pro',         'Lenovo',   '16ACH6', 'Gaming Laptop RTX3070',            1599.99, 24, 3,  7),
('XPS 13',               'Dell',     '9315',   '13.4\" OLED i7',                    1099.99, 24, 4,  3),
('Inspiron 15',          'Dell',     '3520',   'Core i5 16GB',                      799.99, 24, 4,  3),
('WH-1000XM5',           'Sony',     NULL,     'Noise Cancelling Headphones',       349.99, 24, 5,  4),
('WF-C700N',             'Sony',     NULL,     'Wireless Earbuds',                   99.99, 24, 5,  4),
('LinkBuds S',           'Sony',     NULL,     'Compact True Wireless',             129.99, 24, 5,  4),
('EOS M50',              'Canon',    'Mark II','Mirrorless Camera',                 699.99, 24, 6,  5),
('EOS R10',              'Canon',    NULL,     'APS-C Mirrorless',                  1099.99, 24, 6,  5),
('PowerShot G7X',        'Canon',    'III',    'Compact Digital',                   599.99, 24, 6,  5),
('Nintendo Switch',      'Nintendo', NULL,     'Console Neon Red/Blue',             299.99, 12, 7,  7),
('Nintendo Switch OLED', 'Nintendo', NULL,     'OLED White Edition',                349.99, 12, 7,  7),
('PlayStation 5',        'Sony',     NULL,     'Digital Edition',                   499.99, 24, 7,  7),
('Air Fryer 5L',         'HomeKitch','AF5',    'Digital Air Fryer',                 129.99, 12, 8,  6),
('Blender 700W',         'HomeKitch','BL7',    'Glass Jar Blender',                  69.99, 12, 8,  6),
('Toaster 2-Slice',      'HomeKitch','TS2',    'Compact Toaster',                    49.99, 12, 8,  6),
('The Pragmatic Programmer','Addison','2nd',   'Classic Programming Book',           39.99,  0, 9,  8),
('Clean Code',           'Prentice', '1st',    'Robert Martin',                      44.99,  0, 9,  8),
('Head First Java',      'OReilly',  '3rd',    'Learning Java visually',             49.99,  0, 9,  8),
('Nivea Cream 150ml',    'Nivea',    NULL,     'Universal cream',                     9.99,  0,10,  9),
('LOréal Shampoo 400ml', 'LOréal',   NULL,     'Revitalizing shampoo',               11.99,  0,10,  9),
('Maybelline Mascara',   'Maybelline',NULL,    'Volume Express',                     13.99,  0,10,  9),
('Cotton T-Shirt',       'Basic',    'TS100',  '100% Cotton M',                      14.99,  0,11, 10),
('Jeans Slim Fit',       'DenimCo',  'J200',   'Blue slim fit',                      49.99,  0,11, 10),
('Hoodie Unisex',        'Urban',    'H300',   'Black hoodie',                       34.99,  0,11, 10),
('Vacuum Cleaner 1200W', 'CleanHome','VC12',   'Bagless vacuum',                    199.99, 24,12, 11),
('Steam Iron 2600W',     'CleanHome','IR26',   'Ceramic soleplate',                  59.99, 24,12, 11),
('Air Purifier',         'CleanHome','AP10',   'HEPA filter',                       159.99, 24,12, 11),
('Football Size 5',      'SportStar','FB5',    'Training football',                  24.99, 12,13, 12),
('Tennis Racket',        'Wilson',   'WRK1',   'Pro Staff',                         129.99, 24,13, 12),
('Yoga Mat',             'Adidas',   'YMat',   '6mm thickness',                      29.99, 12,13, 12),
('LEGO Classic Set',     'LEGO',     '11021',  '1500 pieces',                        59.99, 12,14, 13),
('LEGO Technic Car',     'LEGO',     '42141',  'McLaren F1',                        189.99, 12,14, 13),
('Toy Car',              'HotWheels','HW100',  'Die-cast mini car',                   4.99,  0,14, 13),
('Car Phone Holder',     'AutoGear', 'APH1',   'Dashboard mount',                    12.99, 12,15, 14),
('Car Charger',          'AutoGear', 'CC20',   'USB-C Fast Charger',                 19.99, 12,15, 14),
('LED Headlights',       'AutoGear', 'LED500', 'H7 bulbs pair',                      39.99, 12,15, 14),
('Garden Hose 20m',      'Gardena',  'GH20',   'Flexible garden hose',               24.99, 12,15, 15),
('Lawn Mower 1600W',     'Gardena',  'LM16',   'Electric mower',                    249.99, 24,15, 15),
('Garden Gloves',        'Gardena',  'GG10',   'Durable gloves',                      9.99, 12,15, 15),
('Cookbook Recipes',     'Jamie Oliver', 'COOK1', 'Healthy recipes',                 29.99,  0, 9,  8),
('Gaming Mouse',         'Logitech', 'G502',   'Wireless Gaming Mouse',              79.99, 24, 7,  7),
('Smartwatch Versa 4',   'Fitbit',   NULL,     'Fitness Smartwatch',                199.99, 24, 2,  2),
('Wireless Keyboard',    'Logitech', 'K380',   'Compact Keyboard',                   49.99, 24, 5,  4);

