CREATE DATABASE Emag
USE Emag

ALTER TABLE [USER]
(
	[USER_ID] INT IDENTITY (1,1) PRIMARY KEY,
	USERNAME VARCHAR(50) NOT NULL UNIQUE,
	EMAIL VARCHAR(100) NOT NULL UNIQUE,
	[PASSWORD] VARCHAR(255) NOT NULL,
	FIRST_NAME VARCHAR(50) NOT NULL,
	LAST_NAME VARCHAR(50)NOT NULL,
	PHONE_NUMBER VARCHAR(20),
	GENDER CHAR(1) NOT NULL CHECK (GENDER IN ('F', 'M')),
	BIRTH_DATE DATE NOT NULL,
	COUNTRY VARCHAR(50) NOT NULL,
	CITY VARCHAR(50) NOT NULL
)


CREATE TABLE [ORDER]
(
	ORDER_ID INT IDENTITY (1,1) PRIMARY KEY,
	ORDER_NUMBER VARCHAR(50) NOT NULL UNIQUE,
	[USER_ID] INT NOT NULL FOREIGN KEY REFERENCES [USER]([USER_ID]),
	ORDER_DATE DATE NOT NULL,
	[STATUS] VARCHAR(30) NOT NULL,
	POSTAL_CODE VARCHAR(20),
	DELIVERY_ADDRESS VARCHAR(100) NOT NULL,
	TOTAL_AMOUNT DECIMAL(10,2) NOT NULL
)



CREATE TABLE PAYMENT
(
	PAYMENT_ID INT IDENTITY (1,1) PRIMARY KEY,
	ORDER_ID INT NOT NULL FOREIGN KEY REFERENCES [ORDER](ORDER_ID),
	METHOD VARCHAR(50) NOT NULL,
	AMOUNT DECIMAL(10,2) NOT NULL,
	CURRENCY VARCHAR(10) NOT NULL,
	STATUS VARCHAR(30) NOT NULL,
	PAID_AT DATE
)

CREATE TABLE SELLER
(
	SELLER_ID INT IDENTITY (1,1) PRIMARY KEY,
	COMPANY_NAME VARCHAR(100) NOT NULL,
	COMPANY_EMAIL VARCHAR(100) NOT NULL UNIQUE,
	AVERAGE_RATING DECIMAL(3,2) CHECK (AVERAGE_RATING BETWEEN 0 AND 5),
	COUNTRY VARCHAR(50)
)

CREATE TABLE CATEGORY
(
	CATEGORY_ID INT IDENTITY (1,1) PRIMARY KEY,
	CATEGORY_NAME VARCHAR(50) NOT NULL UNIQUE,
	[DESCRIPTION] VARCHAR(255)
)

CREATE TABLE PRODUCT
(
	PRODUCT_ID INT IDENTITY (1,1) PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
	BRAND VARCHAR(50),
	MODEL VARCHAR(50),
	[DESCRIPTION] VARCHAR(255),
	PRICE DECIMAL(10,2) NOT NULL CHECK (PRICE >= 0),
	WARRANTY_MONTH INT CHECK (WARRANTY_MONTH >= 0),
	SELLER_ID INT NOT NULL FOREIGN KEY REFERENCES SELLER(SELLER_ID),
	CATEGORY_ID INT NOT NULL FOREIGN KEY REFERENCES CATEGORY(CATEGORY_ID)
)


CREATE TABLE REVIEW
(
	REVIEW_ID INT IDENTITY (1,1) PRIMARY KEY,
	TITLE VARCHAR(100) NOT NULL,
	RATING INT CHECK (RATING BETWEEN 1 AND 5) NOT NULL,
	COMMENT VARCHAR(255) NOT NULL,
	CREATED_AT DATE NOT NULL,
	USER_ID INT NOT NULL FOREIGN KEY REFERENCES [USER]([USER_ID]),
	PRODUCT_ID INT NOT NULL FOREIGN KEY REFERENCES PRODUCT(PRODUCT_ID)
)



CREATE TABLE ORDER_PRODUCT
(
	ORDER_ID INT NOT NULL FOREIGN KEY REFERENCES [ORDER](ORDER_ID),
	PRODUCT_ID INT NOT NULL FOREIGN KEY REFERENCES PRODUCT(PRODUCT_ID),
	QUANTITY INT NOT NULL CHECK (QUANTITY > 0),
	UNIT_PRICE DECIMAL(10,2) NOT NULL CHECK (UNIT_PRICE >= 0),
	PRIMARY KEY (ORDER_ID, PRODUCT_ID)
)

